from typing import Protocol
from uuid import UUID


class CRMAdapter(Protocol):
    async def transform_inbound(self, raw: dict) -> dict: ...
    async def sync_outcome(self, lead_id: UUID, outcome: dict) -> dict: ...
    async def sync_site_visit(self, lead_id: UUID, status: str) -> dict: ...
