from typing import Protocol
from uuid import UUID


class NotificationPort(Protocol):
    async def push_realtime(self, user_id: UUID, event: dict) -> None: ...
    async def send_whatsapp_alert(self, phone: str, alert: dict) -> None: ...
    async def queue_email_digest(self, user_id: UUID, entry: dict) -> None: ...
