from typing import Protocol
from uuid import UUID


class StoragePort(Protocol):
    async def upload(self, tenant_id: UUID, path: str, data: bytes, content_type: str) -> str: ...
    async def download(self, tenant_id: UUID, path: str) -> bytes: ...
    async def delete(self, tenant_id: UUID, path: str) -> None: ...
