from typing import Protocol
from uuid import UUID


class TelephonyPort(Protocol):
    async def initiate_call(self, lead_id: UUID, phone: str, caller_id: str) -> dict: ...
    async def transfer_call(self, call_id: UUID, target_phone: str, context: str) -> dict: ...
    async def end_call(self, call_id: UUID) -> None: ...
