from typing import Protocol


class WhatsAppPort(Protocol):
    async def send_template(self, to: str, template_name: str, params: dict) -> dict: ...
    async def send_message(self, to: str, content: str, from_number: str) -> dict: ...
    async def handle_inbound(self, webhook_payload: dict) -> dict: ...
