"""CLI commands for the Loop engineering layer.

    tvastar loop init <Pattern> [--name NAME] [--out PATH]
    tvastar loop run  <ref>                   e.g. .tvastar/loops/ci.py:loop
    tvastar loop status <ref>
    tvastar loop audit <ref>

Werner principle: fail fast at configuration time, not at 2am.
Every command validates inputs before touching any runtime state.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from . import Loop, LoopRun
    from .audit import ReadinessLevel

# ---------------------------------------------------------------------------
# Available patterns (used by init + error messages)
# ---------------------------------------------------------------------------

_PATTERNS: dict[str, str] = {
    "CISweeper": "ci-sweeper",
    "PRBabysitter": "pr-babysitter",
    "DailyTriage": "daily-triage",
    "DependencySweeper": "dependency-sweeper",
    "PostMergeCleanup": "post-merge-cleanup",
    "ChangelogDrafter": "changelog-drafter",
    "MakerChecker": "maker-checker",
}

# ---------------------------------------------------------------------------
# Scaffold templates
# ---------------------------------------------------------------------------

_STANDARD_TEMPLATE = '''\
"""Loop: {name}

Scaffold generated by `tvastar loop init {pattern}`.
Edit model= and review the schedule/handoff before deploying.
"""
from tvastar.loop.patterns import {pattern}
from tvastar.loop.handoff import LogHandoff

# Replace MockModel with your real model:
#   from tvastar.model.anthropic import AnthropicModel
#   model = AnthropicModel("claude-sonnet-4-6")
from tvastar.model.mock import MockModel

model = MockModel()

loop = {pattern}(
    model=model,
    # schedule="*/15 * * * *",  # override the default schedule if needed
    # handoff=LogHandoff(),      # LogHandoff is the default; swap for Slack/PagerDuty
    # max_iterations=3,
    # cancel_after=300.0,        # seconds — strongly recommended for production (L2+)
    # extra_instructions="",
)
'''

_MAKER_CHECKER_TEMPLATE = '''\
"""Loop: {name}

Two-agent Maker/Checker scaffold.
Maker proposes; Checker independently verifies before SUCCESS is declared.
"""
from tvastar.loop.patterns import MakerChecker
from tvastar.loop.handoff import LogHandoff

# You can use different models: faster model for Maker, stronger for Checker.
#   from tvastar.model.anthropic import AnthropicModel
#   maker_model  = AnthropicModel("claude-haiku-4-5-20251001")
#   checker_model = AnthropicModel("claude-sonnet-4-6")
from tvastar.model.mock import MockModel

maker_model = MockModel()
checker_model = MockModel()

loop = MakerChecker(
    maker_model=maker_model,
    checker_model=checker_model,
    goal="<describe what should be made and verified>",
    # schedule="@manual",          # default: manual trigger only
    # handoff=LogHandoff(),
    # max_rounds=3,                # Maker+Checker cycles before HANDOFF
    # cancel_after=600.0,
    # extra_maker_instructions="",
    # extra_checker_instructions="",
)
'''


def _scaffold(pattern: str, name: str) -> str:
    if pattern == "MakerChecker":
        return _MAKER_CHECKER_TEMPLATE.format(name=name)
    return _STANDARD_TEMPLATE.format(pattern=pattern, name=name)


# ---------------------------------------------------------------------------
# Loop loader
# ---------------------------------------------------------------------------


def _load_loop(ref: str) -> "Loop":  # type: ignore[name-defined]
    """Resolve ``file.py:attr`` or ``module:attr`` to a Loop instance."""
    import importlib
    import importlib.util

    from ..errors import TvastarError
    from . import Loop

    target, _, attr = ref.partition(":")
    attr = attr or "loop"

    if target.endswith(".py") or "/" in target or "\\" in target:
        p = Path(target).resolve()
        if not p.exists():
            raise TvastarError(f"Loop file not found: {target}")
        file_spec = importlib.util.spec_from_file_location(p.stem, p)
        if file_spec is None or file_spec.loader is None:
            raise TvastarError(f"Cannot import {target}")
        module = importlib.util.module_from_spec(file_spec)
        sys.modules[p.stem] = module
        file_spec.loader.exec_module(module)  # type: ignore[union-attr]
    else:
        try:
            module = importlib.import_module(target)
        except ImportError as exc:
            raise TvastarError(f"Cannot import {target!r}: {exc}") from exc

    if not hasattr(module, attr):
        available = [k for k, v in vars(module).items() if isinstance(v, Loop)]
        hint = f" Available Loop objects: {available}" if available else ""
        raise TvastarError(f"'{target}' has no attribute '{attr}'.{hint}")

    obj = getattr(module, attr)
    if not isinstance(obj, Loop):
        raise TvastarError(f"'{ref}' resolved to {type(obj).__name__}, expected a Loop instance.")
    return obj


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_init(pattern: str, name: str | None, out: str | None) -> int:
    """Scaffold a loop config file from a named pattern.

    Failure modes handled:
    - Unknown pattern → list available patterns and exit 1
    - Destination file already exists → refuse to overwrite, exit 1
    - Parent directories missing → create them automatically
    """
    if pattern not in _PATTERNS:
        print(
            f"Unknown pattern: {pattern!r}\nAvailable patterns: {', '.join(_PATTERNS)}",
            file=sys.stderr,
        )
        return 1

    loop_name = name or _PATTERNS[pattern]
    safe_name = loop_name.replace("-", "_")

    dest = Path(out) if out else Path(".tvastar") / "loops" / f"{safe_name}.py"

    if dest.exists():
        print(
            f"File already exists: {dest}\n"
            "Remove it first or specify --out to write to a different path.",
            file=sys.stderr,
        )
        return 1

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(_scaffold(pattern, loop_name), encoding="utf-8")

    print(f"Scaffolded {pattern} → {dest}")
    print(f"  1. Edit {dest} — set your model and review the schedule.")
    print(f"  2. Run:  tvastar loop audit {dest}:loop")
    print(f"  3. Run:  tvastar loop run   {dest}:loop")
    return 0


def cmd_run(ref: str) -> int:
    """Trigger a loop once (blocking) and print the result.

    Exit 0 on PASS, exit 1 on any failure state.

    Failure modes handled:
    - Loop file not found → clear error, exit 1
    - Loop SUSPENDED → block with reset instructions, exit 1
    - Run fails (FAIL/HANDOFF/etc.) → print error details, exit 1
    """
    from ..errors import TvastarError

    try:
        loop = _load_loop(ref)
    except TvastarError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    from . import LoopState

    if loop.state == LoopState.SUSPENDED:
        print(
            f"Loop '{loop.name}' is SUSPENDED (circuit breaker tripped after "
            f"{loop.config.circuit_breaker_limit} consecutive failures).\n"
            "To resume: call loop.reset() in a Python script.",
            file=sys.stderr,
        )
        return 1

    async def _go() -> int:
        run = await loop.trigger()
        _print_run(run)
        return 0 if run.ok else 1

    return asyncio.run(_go())


def cmd_status(ref: str) -> int:
    """Show current state, last run, and next scheduled time for a loop."""
    from ..errors import TvastarError

    try:
        loop = _load_loop(ref)
    except TvastarError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    _print_status(loop)
    return 0


def cmd_audit(ref: str) -> int:
    """Score a loop's readiness (L0→L3) and print the report.

    Exit 0 only at L3 AUTONOMOUS (production-ready).
    Suitable for use in CI/pre-deploy gates:
        tvastar loop audit .tvastar/loops/ci.py:loop || exit 1
    """
    from ..errors import TvastarError

    try:
        loop = _load_loop(ref)
    except TvastarError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    from .audit import audit_loop

    report = audit_loop(loop)
    _print_audit(loop, report)
    return 0 if report.is_production_ready else 1


# ---------------------------------------------------------------------------
# Output formatters
# ---------------------------------------------------------------------------


def _print_run(run: "LoopRun") -> None:  # type: ignore[name-defined]
    import time as _time

    dur = run.duration
    dur_s = f"{dur:.1f}s" if dur is not None else "?"
    ts_raw = run.ended_at or run.started_at
    ts = _time.strftime("%Y-%m-%d %H:%M:%S UTC", _time.gmtime(ts_raw))
    print(f"\nRun {run.run_id[:8]}  [{run.state.value.upper()}]  {dur_s}  {ts}")

    if run.result_text:
        snippet = run.result_text[:400].replace("\n", " ")
        ellipsis = "…" if len(run.result_text) > 400 else ""
        print(f"  Result: {snippet}{ellipsis}")

    if run.error:
        print(f"  Error:  {run.error}")

    if run.findings:
        print(f"  Findings ({len(run.findings)}):")
        for finding in run.findings:
            sev = getattr(finding.severity, "value", finding.severity)
            print(f"    [{sev.upper()}] {finding.message}")


def _print_status(loop: "Loop") -> None:  # type: ignore[name-defined]
    import time as _time

    from . import LoopState

    _hr = "─" * 52
    print(f"\n{_hr}")
    print(f"  Loop:     {loop.name}")
    print(f"  State:    {loop.state.value.upper()}")
    print(f"  Schedule: {loop.config.schedule}")

    last = loop.last_run()
    if last:
        ts_raw = last.ended_at or last.started_at
        ts = _time.strftime("%Y-%m-%d %H:%M UTC", _time.gmtime(ts_raw))
        dur_s = f"{last.duration:.1f}s" if last.duration is not None else "?"
        print(f"  Last run: [{last.state.value.upper()}]  {ts}  ({dur_s})")
        if last.result_text:
            snippet = last.result_text[:120].replace("\n", " ")
            ellipsis = "…" if len(last.result_text) > 120 else ""
            print(f"            {snippet}{ellipsis}")
    else:
        print("  Last run: (never run)")

    if loop.config.schedule != "@manual" and loop.state not in (
        LoopState.SUSPENDED,
        LoopState.RUNNING,
        LoopState.VERIFYING,
        LoopState.TRIGGERED,
    ):
        try:
            from datetime import datetime, timezone

            from .schedule import next_run_time

            nxt = next_run_time(loop.config.schedule, datetime.now(tz=timezone.utc))
            print(f"  Next run: {nxt.strftime('%Y-%m-%d %H:%M UTC')}")
        except ValueError:
            pass

    if loop.state == LoopState.SUSPENDED:
        print(
            "\n  SUSPENDED — circuit breaker tripped.\n"
            "  To resume: call loop.reset() in a Python script."
        )
    print(f"{_hr}\n")


def _print_audit(loop: "Loop", report: "ReadinessLevel") -> None:  # type: ignore[name-defined]
    _hr = "━" * 52
    badge = f"L{report.level} · {report.name}"

    print(f"\n{_hr}")
    print(f"  Loop Readiness Audit — {loop.name}")
    print(_hr)
    print(f"  Level:  {badge}")
    print(f"  {report.description}")

    if report.passes:
        print()
        print("  Passes:")
        for p in report.passes:
            print(f"    ✓  {p}")

    if report.gaps:
        print()
        print("  Gaps (blocking — fix to advance level):")
        for g in report.gaps:
            print(f"    ✗  {g}")

    if report.warnings:
        print()
        print("  Warnings (non-blocking):")
        for w in report.warnings:
            print(f"    ⚠  {w}")

    production = "YES — this loop can run unattended." if report.is_production_ready else "NO"
    print()
    print(f"  Production-ready: {production}")
    print(f"{_hr}\n")


__all__ = ["cmd_init", "cmd_run", "cmd_status", "cmd_audit"]
